// Constants - Department definitions
import { Department } from '@/src/domain/entities/Document';

export const DEPARTMENTS: Department[] = [
  'PUR',
  'STO',
  'ER',
  'SURG',
  'CRO',
  'STR',
  'HSA',
  'ADMISSION',
  'AMB',
  'CAS',
  'PHA',
  'MED',
  'MRD',
  'PED',
  'OBG',
  'LAB',
  'MAI',
  'SKIN',
  'CCO',
  'HOU',
  'CHK',
  'EYE',
  'ENT',
  'CAR',
  'XRD',
  'DNT',
  'HD',
  'ICU',
  'CATH',
  'LR',
  'OR',
  'CSSD',
  'MEM',
  'NICU',
  'NSY',
  'HR',
  'MRA',
  'IPC',
  'ACC',
  'FIN',
  'QC',
  'COM',
  'PHY',
  'GI',
  'W10',
  'W11',
  'W12',
  'NIGHT OBG',
  'NIGHT MED',
  'NIGHT PED',
];

// Department labels with Thai names
export const DEPARTMENT_LABELS: Record<Department, string> = {
  'PUR': 'แผนกจัดซื้อ (PUR)',
  'STO': 'แผนกพัสดุ (STO)',
  'ER': 'ศูนย์ฉุกเฉินและอุบัติเหตุ (ER)',
  'SURG': 'แผนกศัลยกรรมและศัลยกรรมกระดูกและข้อ (SURG)',
  'CRO': 'หน่วยงานลูกค้าสัมพันธ์ (CRO)',
  'STR': 'หน่วยงานเคลื่อนย้ายผู้ป่วย (STR)',
  'HSA': 'แผนก Hospital Service Agent (HSA)',
  'ADMISSION': 'ศูนย์บริการลูกค้าประกันและรับผู้ป่วยใน (ADMISSION)',
  'AMB': 'หน่วยงานรถพยาบาล (AMB)',
  'CAS': 'แผนกการเงินผู้ป่วยนอก (CAS)',
  'PHA': 'แผนกเภสัชกรรม (PHA)',
  'MED': 'แผนกอายุรกรรม (MED)',
  'MRD': 'แผนกเอกสารทางการแพทย์ (MRD)',
  'PED': 'ศูนย์กุมารเวช (PED)',
  'OBG': 'ศูนย์สูติ-นรีเวช (OBG)',
  'LAB': 'แผนกห้องปฏิบัติการทางการแพทย์ (LAB)',
  'MAI': 'แผนกซ่อมบำรุง (MAI)',
  'SKIN': 'ศูนย์ผิวหนังเลเซอร์และความงาม (SKIN)',
  'CCO': 'แผนก Contact Center and Operator (CCO)',
  'HOU': 'แผนกแม่บ้าน (HOU)',
  'CHK': 'ศูนย์ตรวจสุขภาพ (CHK)',
  'EYE': 'ศูนย์ตา (EYE)',
  'ENT': 'ศูนย์หู คอ จมูก (ENT)',
  'CAR': 'ศูนย์โรคหัวใจ (CAR)',
  'XRD': 'ศูนย์เอกซเรย์และภาพวินิจฉัย (XRD)',
  'DNT': 'ศูนย์ทันตกรรม (DNT)',
  'HD': 'แผนกไตเทียม (HD)',
  'ICU': 'แผนกผู้ป่วยวิกฤต (ICU)',
  'CATH': 'แผนกตรวจสวนหัวใจ (CATH)',
  'LR': 'ห้องคลอด (LR)',
  'OR': 'แผนกห้องผ่าตัด (OR)',
  'CSSD': 'แผนกจ่ายกลาง (CSSD)',
  'MEM': 'แผนกเครื่องมือแพทย์ (MEM)',
  'NICU': 'แผนกทารกแรกเกิดวิกฤติ (NICU)',
  'NSY': 'แผนกทารกแรกเกิด (NSY)',
  'HR': 'แผนกบริหารทรัพยากรบุคคล (HR)',
  'MRA': 'แผนกตรวจสอบเวชระเบียน (MRA)',
  'IPC': 'ศูนย์ประสานงานลูกค้าฝ่ายต่างประเทศ (IPC)',
  'ACC': 'แผนกบัญชี (ACC)',
  'FIN': 'แผนกการเงิน (FIN)',
  'QC': 'ศูนย์คุณภาพ (QC)',
  'COM': 'แผนกคอมพิวเตอร์และเทคโนโลยีสารสนเทศ (COM)',
  'PHY': 'ศูนย์เวชศาสตร์ฟื้นฟู (PHY)',
  'GI': 'แผนกทางเดินอาหาร (GI)',
  'W10': 'แผนกผู้ป่วยใน WARD 10/14 (W10)',
  'W11': 'แผนกผู้ป่วยใน WARD 11/15 (W11)',
  'W12': 'แผนกผู้ป่วยใน WARD 12/16 (W12)',
  'NIGHT OBG': 'คลินิกกลางคืนสูตินารี (NIGHT OBG)',
  'NIGHT MED': 'คลินิกกลางคืนอายุรกรรม (NIGHT MED)',
  'NIGHT PED': 'คลินิกกลางคืนกุมารเวช (NIGHT PED)',
};
